#' Heatmap of Consensus Motif Inclusivity
#'
#' This function creates a heatmap to visualize the inclusivity of motifs 
#' across conditions or regression models based on the output of the 
#' \code{consensus_motifs} function.
#'
#' @param consensus_output A named list generated by the \code{consensus_motifs}
#'  function. The names of the list represent either conditions or regression 
#'  models, and the elements contain named vectors of motif inclusivity 
#'  percentages.
#'
#' @return A ggplot2 object representing the heatmap.
#'
#' @export
consensus_motifs_heatmap <- function(consensus_output) {
  
  if ("LM" %in% names(consensus_output) || "SVM" %in% names(consensus_output) ||
      "PLS" %in% names(consensus_output) || "Randomized_lasso" %in% 
      consensus_output) {
    x_label <- "Regressors"
    title <- "Heatmap of Motif Inclusivity Across Conditions"
  }
  else {
    x_label <- "Conditions"
    title <- "Heatmap of Motif Inclusivity Across Regression Models"
    
  }
  
  all_data <- lapply(names(consensus_output), function(condition) {
    data.frame(
      Condition = condition,
      Motif = names(consensus_output[[condition]]),
      Frequency = unname(consensus_output[[condition]])
    )
  })
  long_df <- do.call(rbind, all_data)
  
  long_df$Condition <- factor(long_df$Condition, levels = 
                                unique(long_df$Condition))
  long_df$Motif <- factor(long_df$Motif, levels = unique(long_df$Motif))
  
  p <- ggplot(long_df, aes(x = Condition, y = Motif, fill = Frequency)) +
    geom_tile(color = "white") +
    scale_fill_gradient(
      low = "white",
      high = "blue",
      name = "Inclusivity (%)",
      limits = c(0, 100),
      oob = scales::squish
    ) +
    theme_minimal(base_size = 14) +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1, size = 14),
      axis.text.y = element_text(size = 8),
      axis.title.x = element_text(size = 16),
      axis.title.y = element_text(size = 16),
      plot.title = element_text(size = 18, face = "bold"),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.ticks = element_blank()
    ) +
    labs(
      x = x_label,
      y = "Motifs",
      title = title
    ) +
    coord_fixed(ratio = length(unique(long_df$Condition)) / 
                  length(unique(long_df$Motif)))
  
  p +
    
    geom_segment(aes(x = as.numeric(Condition) - 0.5, xend = 
                       as.numeric(Condition) - 0.5,
                     y = min(as.numeric(Motif)) - 0.5, yend = 
                       max(as.numeric(Motif)) + 0.5),
                 color = "black") +
    
    
    geom_segment(aes(x = min(as.numeric(Condition)) - 0.5, 
                     xend = max(as.numeric(Condition)) + 0.5,
                     y = as.numeric(Motif) - 0.5,
                     yend = as.numeric(Motif) - 0.5),
                 color = "black") +
    
    geom_segment(aes(x = min(as.numeric(Condition)) - 0.5, 
                     xend = max(as.numeric(Condition)) + 0.5,
                     y = max(as.numeric(Motif)) + 0.5, 
                     yend = max(as.numeric(Motif)) + 0.5),
                 color = "black") +
    
    geom_segment(aes(x = max(as.numeric(Condition)) + 0.5, 
                     xend = max(as.numeric(Condition)) + 0.5,
                     y = min(as.numeric(Motif)) - 0.5, 
                     yend = max(as.numeric(Motif)) + 0.5),
                 color = "black")
}
