#' Heatmap of Consensus Motif Inclusivity
#'
#' This function creates a heatmap to visualize the inclusivity of motifs 
#' across conditions or regression models based on the output of the 
#' \code{consensus_motifs} function.
#'
#' @param consensus_output A named list generated by the \code{consensus_motifs}
#'  function. The names of the list represent either conditions or regression 
#'  models, and the elements contain named vectors of motif inclusivity 
#'  percentages.
#'
#' @return A ggplot2 object representing the heatmap.
#'
#' @export
consensus_motifs_heatmap <- function(consensus_output) {
    if (any(c("LM", "SVM", "PLS", "Randomized_lasso") %in% names(consensus_output))) {
        x_label <- "Regressors"
        title <- "Heatmap of Motif Inclusivity Across Conditions"
    } else {
        x_label <- "Conditions"
        title <- "Heatmap of Motif Inclusivity Across Regression Models"
    }
    
    all_data <- lapply(names(consensus_output), function(condition) {
        data.frame(
            Condition = condition,
            Motif = names(consensus_output[[condition]]),
            Frequency = unname(consensus_output[[condition]])
        )
    })
    long_df <- do.call(rbind, all_data)
    
    long_df$Condition <- factor(long_df$Condition, levels = unique(long_df$Condition))
    long_df$Motif <- factor(long_df$Motif, levels = unique(long_df$Motif))
    
    matrix <- reshape2::acast(long_df, Motif ~ Condition, value.var = "Frequency", fill = 0)
    
    color_fun <- circlize::colorRamp2(c(0, 50, 100), c("white", "lightblue", "blue"))
    
    heatmap <- Heatmap(
        matrix,
        name = "Inclusivity (%)",
        col = color_fun,
        cluster_rows = FALSE,
        cluster_columns = FALSE,
        row_names_side = "left",
        row_names_gp = gpar(fontsize = 8),
        column_names_gp = gpar(fontsize = 10),
        column_names_rot = 45,
        width = unit(10, "cm"),
        height = unit(10, "cm"),
        row_title = "Motifs",
        row_title_side = "left",
        column_title = x_label,
        column_title_side = "bottom",
        heatmap_legend_param = list(
            at = c(0, 25, 50, 75, 100),
            labels = c("0%", "25%", "50%", "75%", "100%"),
            legend_gp = gpar(fontsize = 8)
        )
    )
    
    ComplexHeatmap::draw(
        heatmap,
        heatmap_legend_side = "right",
        annotation_legend_side = "right",
        column_title = title,
        column_title_side = "top",
        column_title_gp = gpar(fontsize = 12, fontface = "bold")
    )
}
