#' Shiny Server Function
#'
#' This server function powers a Shiny application designed for motif analysis 
#' using Position Frequency Matrices (PFMs) and Position Weight Matrices (PWMs).
#' It allows users to convert PFMs to PWMs, load sequence data, and compute 
#' motif scores.
#'
#' @param input List of input objects generated by Shiny's reactive framework, 
#' representing user inputs from the UI.
#' @param output List of output objects used to render reactive outputs, 
#' such as tables, text, and plots.
#' @param session The session object, used to manage the user's Shiny session 
#' (e.g., for reactive programming).
#'
#' @import shiny
#' @importFrom DT renderDT datatable
#' @export
server <- function(input, output, session) {
  observeEvent(input$info, {
    showModal(modalDialog(
      title = "How to use the tool?",
      "Write instructions on how to use the app.",
      easyClose = TRUE,
      footer = modalButton("Close")
    ))
  })
  
  PFMs <- reactiveVal(NULL)
  PWMs <- reactiveVal(NULL)
  dataseq <- reactiveVal(NULL)
  Scores <- reactiveVal(NULL)
  
  observeEvent(input$Conversion_PFM, {
    req(input$gff_file, input$fna_file)
    
    if (input$database_choice == "jaspar" && input$Tax_ID != "") {
      PFMs(get_jaspar_motif(input$Tax_ID))
    } else if (input$database_choice == "mydata") {
      req(input$meme_file) 
      PFMs(PFM_loader(input$meme_file$datapath))
    }
    
    req(PFMs())
    PWMs(PFM2PWM(PFMs()))
    dataseq(get_sequences(input$gff_file$datapath, input$fna_file$datapath))
    
    output$num_motifs <- renderText({ length(PFMs()) })
    output$num_sequences <- renderText({ length(dataseq()) })
    output$operations <- renderText({ length(PWMs()) * length(dataseq()) })
    
    output$List_of_PFMs <- renderDT({
      req(PFMs())
      data.frame(Motifs = names(PFMs()))
    }, selection = "single")
    
    output$List_of_PWMs <- renderDT({
      req(PWMs())
      data.frame(Motifs = names(PWMs()))
    }, selection = "single")
  })
  
  observeEvent(input$List_of_PFMs_rows_selected, {
    selected <- input$List_of_PFMs_rows_selected
    req(selected)
    motif_name <- names(PFMs())[selected]
    output$Selected_PFM <- renderTable(PFMs()[[motif_name]], rownames = TRUE)
  })
  
  observeEvent(input$List_of_PWMs_rows_selected, {
    selected <- input$List_of_PWMs_rows_selected
    req(selected)
    motif_name <- names(PWMs())[selected]
    output$Selected_PWM <- renderTable(PWMs()[[motif_name]], rownames = TRUE)
  })
  
  observeEvent(input$Start_scoring, {
    req(PWMs(), dataseq())
    
    Scores(AllScores(PWMs(), dataseq()))
    
    output$Scores <- renderDT({
      req(Scores())
      datatable(as.data.frame(Scores()), options = list(scrollX = TRUE))
    })
  })
  
  observeEvent(input$Github, {
    browseURL("https://github.com/LeonardoNossa/Motif-regressor.git")
  })
}


server <- function(input, output, session) {
  
  observeEvent(input$info, {
    showModal(modalDialog(
      title = "How to use the tool?",
      "Write instructions on how to use the app.",
      easyClose = TRUE,
      footer = modalButton("Close")
    ))
  })
  
  PFMs <- reactiveVal(NULL)
  PWMs <- reactiveVal(NULL)
  dataseq <- reactiveVal(NULL)
  Scores <- reactiveVal(NULL)
  
  
  observeEvent(input$Conversion_PFM, {
    req(input$gff_file, input$fna_file)
    
    if (input$database_choice == "jaspar" && input$Tax_ID != "") {
      PFMs(get_jaspar_motif(input$Tax_ID))
    } else if (input$database_choice == "mydata") {
      req(input$meme_file) 
      PFMs(PFM_loader(input$meme_file$datapath))
    }
    
    req(PFMs())
    PWMs(PFM2PWM(PFMs()))
    dataseq(get_sequences(input$gff_file$datapath, input$fna_file$datapath))
    
    output$num_motifs <- renderText({ length(PFMs()) })
    output$num_sequences <- renderText({ length(dataseq()) })
    output$operations <- renderText({ length(PWMs()) * length(dataseq()) })
    
    output$List_of_PFMs <- renderDT({
      req(PFMs())
      data.frame(Motifs = names(PFMs()))
    }, selection = "single")
    
    output$List_of_PWMs <- renderDT({
      req(PWMs())
      data.frame(Motifs = names(PWMs()))
    }, selection = "single")
  })
  
  observeEvent(input$List_of_PFMs_rows_selected, {
    selected <- input$List_of_PFMs_rows_selected
    req(selected)
    motif_name <- names(PFMs())[selected]
    output$Selected_PFM <- renderTable(PFMs()[[motif_name]], rownames = TRUE)
  })
  
  observeEvent(input$List_of_PWMs_rows_selected, {
    selected <- input$List_of_PWMs_rows_selected
    req(selected)
    motif_name <- names(PWMs())[selected]
    output$Selected_PWM <- renderTable(PWMs()[[motif_name]], rownames = TRUE)
  })
  
  
  observeEvent(input$Start_scoring, {
    req(PWMs(), dataseq())
    
    Scores(AllScores(PWMs(), dataseq()))
    
    output$Scores <- renderDT({
      req(Scores())
      datatable(as.data.frame(Scores()), options = list(scrollX = TRUE))
    })
  })
  
  observeEvent(input$Github, {
    browseURL("https://github.com/LeonardoNossa/Motif-regressor.git")
  })
}
